---
name: Checm for Updated Docker Image

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/python:3.10
          image: us-west1-docker.pkg.dev/just-fuckin-around/images/python-base:latest

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: us-west1-docker.pkg.dev/just-fuckin-around/images/python-base
          tags: |
            type=sha
          flavor: |
            latest=auto

      - name: Build and push to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: steps.check.outputs.needs-updating == 'true'
