---
name: Build and Push Python Image to Artifact Registry
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-base
      PROJECT_ID: just-fuckin-around
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
