---
name: Build and Push Python Image to Artifact Registry
on:
  push:
    branches:
      - main

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-base
      PROJECT_ID: just-fuckin-around
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: us-west1-docker.pkg.dev/just-fuckin-around/images/python-base
          tags: |
            type=sha
          flavor: |
            latest=auto

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build and push to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
